version: 0.2

phases:
  pre_build:
    commands:
      - echo In the prebuild phase
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`